// Generated with TypeScript 4.9.5 / OpenUI5 1.71.61 using:
//   - responselike@2.0.1
//   - http-cache-semantics@4.1.1
//   - keyv@4.5.4
//   - buffer@5.7.1
//   - url@0.11.0
//   - undici-types@5.26.5
//   - @types/triple-beam@1.3.5
//   - @types/semver@7.5.7
//   - @types/responselike@1.0.3
//   - @types/node@20.11.17
//   - @types/minimatch@3.0.5
//   - @types/keyv@3.1.4
//   - @types/json-schema@7.0.15
//   - @types/http-cache-semantics@4.0.4
//   - @types/cacheable-request@6.0.3
/// <reference path="./resources/zspk/lib/library.d.ts"/>
/// <reference path="./resources/zspk/lib/utils/UrlParameterBuilder.d.ts"/>
/// <reference path="./resources/zspk/lib/utils/StringConstant.d.ts"/>
/// <reference path="./resources/zspk/lib/utils/SpkStatistic.d.ts"/>
/// <reference path="./resources/zspk/lib/utils/SpkTableUtils.d.ts"/>
/// <reference path="./resources/zspk/lib/utils/Network.d.ts"/>
/// <reference path="./resources/zspk/lib/utils/Helper.d.ts"/>
/// <reference path="./resources/zspk/lib/utils/Constant.d.ts"/>
/// <reference path="./resources/zspk/lib/controller/SpkRoot.d.ts"/>
/// <reference path="./resources/zspk/lib/controller/SpkPage.d.ts"/>
/// <reference path="./resources/zspk/lib/models/SpkStorage.d.ts"/>
/// <reference path="./resources/zspk/lib/controller/SpkController.d.ts"/>
/// <reference path="./resources/zspk/lib/control/SpkSmartTableToolbar.d.ts"/>
/// <reference path="./resources/zspk/lib/control/SpkSmartTable.d.ts"/>
/// <reference path="./resources/zspk/lib/control/SpkSmartTable.gen.d.ts"/>
/// <reference path="./resources/zspk/lib/control/SpkSmartResponsiveTable.d.ts"/>
/// <reference path="./resources/zspk/lib/control/SpkSmartAnalyticalTable.d.ts"/>
/// <reference path="./resources/zspk/lib/control/SpkResponsiveTable.d.ts"/>
/// <reference path="./resources/zspk/lib/control/SpkSmartVariantManagement.d.ts"/>
/// <reference path="./resources/zspk/lib/control/SpkOverflowToolbar.d.ts"/>
/// <reference path="./resources/zspk/lib/control/SpkOverflowToolbar.gen.d.ts"/>
/// <reference path="./resources/zspk/lib/control/SpkFilterManager.d.ts"/>
/// <reference path="./resources/zspk/lib/control/SpkDependencyComboBox.d.ts"/>
/// <reference path="./resources/zspk/lib/control/SpkAnalyticalTable.d.ts"/>
/// <reference path="./resources/zspk/lib/utils/Validator.d.ts"/>
/// <reference path="./resources/zspk/lib/control/SpkSmartTableToolbar.gen.d.ts"/>
/// <reference path="./resources/zspk/lib/utils/Formatter.d.ts"/>